---
title: Voeg een enorme emoji toe
hero_image: images/banner.png
description: Voeg een enorme emoji toe aan een HTML-element.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Voeg een enorme emoji toe
