title: Ajouter un énorme emoji
hero_image: images/banner.png
description: Ajoute un énorme emoji à un élément HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter un énorme emoji
